{% extends 'includes/landing-layout.swig' %}

{% block header %}
<div class="header-image bg-img-fact">
  <div class="container">
    <h1 class="logo">
      <strong class="title">J<font color="#962B2B">S</font>pare NoSQL Database</strong><strong class="subtitle">&nbsp;</strong>&nbsp;Minimalist and functional
    </h1>
    <h4>Please wait, we are working....</h4>
  </div>
</div>
{% endblock %}

{% block main %}
<!-- Main container -->

<!-- END Main container -->
{% endblock %}